spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/crush?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 1000
      min-idle: 100


  thymeleaf:
    suffix: .html
    cache: false

  redis:
    password: "123456."
    jedis:
      pool:
        max-active: 1000
        min-idle: 100
    sentinel:
      master: redis-master
      nodes: [47.100.57.4:26379,47.100.57.4:26380,47.100.57.4:26381]

  rabbitmq:
    username: guest
    password: guest
    port: 5672
    addresses: 127.0.0.1
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      simple:
        max-concurrency: 10
        concurrency: 5
        acknowledge-mode: manual
      direct:
        prefetch: 1
    virtual-host: /
    template:
      mandatory: true




mybatis:
  configuration:
    # 开启下划线变成驼峰
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
  mapper-locations: classpath:mapper/*.xml
